/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a application_adaptor application.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef APPLICATION_ADAPTOR_H
#define APPLICATION_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

class AppInterfaceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.example.Examples.AppInterface")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.example.Examples.AppInterface\">\n"
"    <method name=\"play\"/>\n"
"    <arg direction=\"in\" type=\"s\" name=\"songPath\"/>\n"
"    </method>\n"
"    <method name=\"pause\"/>\n"
"    <arg direction=\"in\" type=\"s\" name=\"songPath\"/>\n"
"    </method>\n"
"    <method name=\"nextsong\"/>\n"
"    <method name=\"prevsong\"/>\n"
"    <method name=\"stop\"/>\n"
"    <arg direction=\"in\" type=\"s\" name=\"songPath\"/>\n"
"    </method>\n"
"  </interface>\n"
"")
public:
    AppInterfaceAdaptor(QObject *parent);
    virtual ~AppInterfaceAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void play(const QString &songPath);
    void pause(const QString &songPath);
    void nextsong();
    void prevsong();
    void stop(const QString &songPath);

};

#endif
